"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ATTENDANCE_REQUEST_STATUS_ENUM = exports.ATTENDANCE_TYPE_ENUM = void 0;
var ATTENDANCE_TYPE_ENUM;
(function (ATTENDANCE_TYPE_ENUM) {
    ATTENDANCE_TYPE_ENUM["IN"] = "in";
    ATTENDANCE_TYPE_ENUM["OUT"] = "out";
})(ATTENDANCE_TYPE_ENUM || (exports.ATTENDANCE_TYPE_ENUM = ATTENDANCE_TYPE_ENUM = {}));
var ATTENDANCE_REQUEST_STATUS_ENUM;
(function (ATTENDANCE_REQUEST_STATUS_ENUM) {
    ATTENDANCE_REQUEST_STATUS_ENUM["OPENING"] = "opening";
    ATTENDANCE_REQUEST_STATUS_ENUM["ACCEPTED"] = "accepted";
    ATTENDANCE_REQUEST_STATUS_ENUM["REJECTED"] = "rejected";
})(ATTENDANCE_REQUEST_STATUS_ENUM || (exports.ATTENDANCE_REQUEST_STATUS_ENUM = ATTENDANCE_REQUEST_STATUS_ENUM = {}));
//# sourceMappingURL=attendance.js.map