"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LOYALTY_RULE_TAX_MODE_ENUM = exports.LOYALTY_RULE_REWARD_POINT_MODE_ENUM = exports.LOYALTY_RULE_MODE_ENUM = void 0;
var LOYALTY_RULE_MODE_ENUM;
(function (LOYALTY_RULE_MODE_ENUM) {
    LOYALTY_RULE_MODE_ENUM["AUTO"] = "automatic";
    LOYALTY_RULE_MODE_ENUM["WITH_CODE"] = "with_a_promotion_code";
})(LOYALTY_RULE_MODE_ENUM || (exports.LOYALTY_RULE_MODE_ENUM = LOYALTY_RULE_MODE_ENUM = {}));
var LOYALTY_RULE_REWARD_POINT_MODE_ENUM;
(function (LOYALTY_RULE_REWARD_POINT_MODE_ENUM) {
    LOYALTY_RULE_REWARD_POINT_MODE_ENUM["ORDER"] = "per_order";
    LOYALTY_RULE_REWARD_POINT_MODE_ENUM["MONEY"] = "per_vnd_spent";
    LOYALTY_RULE_REWARD_POINT_MODE_ENUM["UNIT"] = "per_unit_paid";
})(LOYALTY_RULE_REWARD_POINT_MODE_ENUM || (exports.LOYALTY_RULE_REWARD_POINT_MODE_ENUM = LOYALTY_RULE_REWARD_POINT_MODE_ENUM = {}));
var LOYALTY_RULE_TAX_MODE_ENUM;
(function (LOYALTY_RULE_TAX_MODE_ENUM) {
    LOYALTY_RULE_TAX_MODE_ENUM["INCL"] = "included";
    LOYALTY_RULE_TAX_MODE_ENUM["EXCL"] = "excluded";
})(LOYALTY_RULE_TAX_MODE_ENUM || (exports.LOYALTY_RULE_TAX_MODE_ENUM = LOYALTY_RULE_TAX_MODE_ENUM = {}));
//# sourceMappingURL=loyalty-rule.js.map