"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LOYALTY_PROGRAM_TRIGGER_ENUM = exports.LOYALTY_PROGRAM_TYPE_ENUM = exports.LOYALTY_PROGRAM_APPLY_ON_ENUM = void 0;
var LOYALTY_PROGRAM_APPLY_ON_ENUM;
(function (LOYALTY_PROGRAM_APPLY_ON_ENUM) {
    LOYALTY_PROGRAM_APPLY_ON_ENUM["CURRENT"] = "current";
    LOYALTY_PROGRAM_APPLY_ON_ENUM["FUTURE"] = "future";
    LOYALTY_PROGRAM_APPLY_ON_ENUM["BOTH"] = "both";
})(LOYALTY_PROGRAM_APPLY_ON_ENUM || (exports.LOYALTY_PROGRAM_APPLY_ON_ENUM = LOYALTY_PROGRAM_APPLY_ON_ENUM = {}));
var LOYALTY_PROGRAM_TYPE_ENUM;
(function (LOYALTY_PROGRAM_TYPE_ENUM) {
    LOYALTY_PROGRAM_TYPE_ENUM["COUPONS"] = "coupons";
    LOYALTY_PROGRAM_TYPE_ENUM["LOYALTY"] = "loyalty_cards";
    LOYALTY_PROGRAM_TYPE_ENUM["PROMOTION"] = "promotions";
    LOYALTY_PROGRAM_TYPE_ENUM["PROMOTION_CODE"] = "discount_code";
    LOYALTY_PROGRAM_TYPE_ENUM["BUY_X_GET_Y"] = "buy_x_get_y";
    LOYALTY_PROGRAM_TYPE_ENUM["NEXT_ORDER_COUPONS"] = "next_order_coupons";
})(LOYALTY_PROGRAM_TYPE_ENUM || (exports.LOYALTY_PROGRAM_TYPE_ENUM = LOYALTY_PROGRAM_TYPE_ENUM = {}));
var LOYALTY_PROGRAM_TRIGGER_ENUM;
(function (LOYALTY_PROGRAM_TRIGGER_ENUM) {
    LOYALTY_PROGRAM_TRIGGER_ENUM["AUTO"] = "automatic";
    LOYALTY_PROGRAM_TRIGGER_ENUM["WITH_CODE"] = "use_a_code";
})(LOYALTY_PROGRAM_TRIGGER_ENUM || (exports.LOYALTY_PROGRAM_TRIGGER_ENUM = LOYALTY_PROGRAM_TRIGGER_ENUM = {}));
//# sourceMappingURL=loyalty-program.js.map