"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RATING_CRITERIA_CONTEXT_ENUMS = void 0;
var RATING_CRITERIA_CONTEXT_ENUMS;
(function (RATING_CRITERIA_CONTEXT_ENUMS) {
    RATING_CRITERIA_CONTEXT_ENUMS["PRODUCT"] = "product";
    RATING_CRITERIA_CONTEXT_ENUMS["SURVEY"] = "survey";
    RATING_CRITERIA_CONTEXT_ENUMS["POST"] = "post";
    RATING_CRITERIA_CONTEXT_ENUMS["SERVICE_EXPERIENCE"] = "service_experience";
    RATING_CRITERIA_CONTEXT_ENUMS["STAFF_PERFORMANCE"] = "staff_performance";
    RATING_CRITERIA_CONTEXT_ENUMS["FACILITY"] = "facility";
    RATING_CRITERIA_CONTEXT_ENUMS["DELIVERY"] = "delivery";
    RATING_CRITERIA_CONTEXT_ENUMS["GENERAL"] = "general";
})(RATING_CRITERIA_CONTEXT_ENUMS || (exports.RATING_CRITERIA_CONTEXT_ENUMS = RATING_CRITERIA_CONTEXT_ENUMS = {}));
//# sourceMappingURL=index.js.map