export * from './errors';
export * from './file.status';
export * from './filter.rule';
export * from './product.state';
export * from './elastic-index';
export * from './order';
export * from './report';
export * from './partner';
export * from './hr';
export * from './table';
export * from './regex';
export * from './team';
export * from './wallet';
export declare const UNIT_TIME: string[];
export declare const SHIPPING_PROVIDER_CONFIG_KEY: {
    GHN: string[];
    GHTK: string[];
};
export declare const PAGINATE_LIMIT_NUMBER = 200;
export declare const MOMENT_VN_TIMEZONE = "Asia/Ho_Chi_Minh";
export declare const DOMAIN_HEADER_KEY = "sipos-x-domain";
export declare const KEYCLOAK_MULTI_CLIENT_SECRET = "webbuilder-client-secret";
