"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.idFieldDataMapping = exports.statusFinancialOrderMapping = exports.paymentGatewayNameMapping = exports.statusFulfillmentOrderMapping = exports.statusOrderMapping = exports.ORDER_HEADER_MAPPING_KEY = exports.HEADER_ORDER_EXPORT = exports.ORDER_HEADER_EXPORT_LINE_ITEM = exports.ORDER_HEADER_DATA_EXPORT = void 0;
const enum_1 = require("../enum");
const elastic_index_1 = require("./elastic-index");
exports.ORDER_HEADER_DATA_EXPORT = [
    'Mã đơn hàng',
    'Chi nhánh',
    'Khách hàng',
    'Kho hàng',
    'Trang thái đơn hàng',
    'Trạng thái giao hàng',
    'Trạng thái thanh toán',
    'Kênh bán hàng',
    'Phương thức thanh toán',
    'Tổng Giảm giá',
    'Mã giảm giá',
    'Đơn vị tiền tệ',
    'Phí vận chuyển',
    'Phí phát sinh',
    'Tổng thuế',
    'Tông tiền',
    'Ngày lên đơn',
    'Phương thức giao hàng',
    'Địa chỉ giao hàng',
    'Địa chỉ thanh toán',
    'Bảng giá',
    'Nhân viên',
    'Thẻ',
    'Mô tả',
];
exports.ORDER_HEADER_EXPORT_LINE_ITEM = [
    'Tên mặt hàng',
    'Số lượng',
    'Giá bán',
    'Giảm giá mặt hàng',
    'Khối lượng',
    'Có thuế',
    'Phần thưởng',
    'Hoàn trả',
    'Tổng thuế mặt hàng',
    'Tông tiền lựa chọn',
];
exports.HEADER_ORDER_EXPORT = [
    ...exports.ORDER_HEADER_DATA_EXPORT,
    ...exports.ORDER_HEADER_EXPORT_LINE_ITEM,
];
exports.ORDER_HEADER_MAPPING_KEY = {
    'Mã đơn hàng': 'code',
    'Chi nhánh': 'branchName',
    'Khách hàng': 'customerName',
    'Kho hàng': 'warehouseName',
    'Trang thái đơn hàng': 'statusName',
    'Trạng thái giao hàng': 'fulfillmentStatusName',
    'Trạng thái thanh toán': 'financialStatusName',
    'Kênh bán hàng': 'saleChannelName',
    'Phương thức thanh toán': 'paymentGatewayName',
    'Tổng Giảm giá': 'discountOrder',
    'Mã giảm giá': 'discountCode',
    'Đơn vị tiền tệ': 'currencyCode',
    'Phí vận chuyển': 'addtionalShippingFee',
    'Phí phát sinh': 'incidentalFee',
    'Tổng thuế': 'taxTotal',
    'Tông tiền': 'total',
    'Ngày lên đơn': 'createdAtFormat',
    'Phương thức giao hàng': 'shippingMethod',
    'Địa chỉ giao hàng': 'addressShipping',
    'Địa chỉ thanh toán': 'addressBilling',
    'Bảng giá': 'priceBookName',
    'Nhân viên': 'staffName',
    Thẻ: 'tags',
    'Mô tả': 'description',
    'Số lượng': 'lineQuantity',
    'Tên mặt hàng': 'lineName',
    'Giá bán': 'lineUnitPrice',
    'Giảm giá mặt hàng': 'lineDiscount',
    'Khối lượng': 'lineWeight',
    'Có thuế': 'lineTaxable',
    'Phần thưởng': 'lineIsGift',
    'Hoàn trả': 'lineRefundable',
    'Tổng thuế mặt hàng': 'lineTaxTotalPirce',
    'Tông tiền lựa chọn': 'lineSelectGroupPrice',
};
exports.statusOrderMapping = {
    [enum_1.OrderStatus.ARCHIVED]: 'Đã lưu trữ',
    [enum_1.OrderStatus.OPEN]: 'Đang xử lý',
    [enum_1.OrderStatus.CANCELED]: 'Đã hủy',
    [enum_1.OrderStatus.COMPLETED]: 'Đã hoàn thành',
};
exports.statusFulfillmentOrderMapping = {
    [enum_1.OrderFulfillmentStatus.OPEN]: 'Chưa thực hiện',
    [enum_1.OrderFulfillmentStatus.PROGRESSING]: 'Đang tiến hành',
    [enum_1.OrderFulfillmentStatus.CANCELLED]: 'Đã hủy',
    [enum_1.OrderFulfillmentStatus.CLOSED]: 'Đã đóng',
    [enum_1.OrderFulfillmentStatus.ERROR]: 'Có lỗi xảy ra',
    [enum_1.OrderFulfillmentStatus.FAILURE]: 'Thất bại',
    [enum_1.OrderFulfillmentStatus.PENDING]: 'Chờ xử lý',
    [enum_1.OrderFulfillmentStatus.SUCCESS]: 'Thành công',
};
exports.paymentGatewayNameMapping = {
    bank: 'Chuyển khoản',
    cash: 'Tiền mặt',
    vietqr: 'Vietqr',
    cod: 'Thu hộ',
    card: 'Thanh toán thẻ',
    vnpayqr: 'VNPay QR',
    point: 'Điểm',
    vnpay: 'VNPay',
};
exports.statusFinancialOrderMapping = {
    [enum_1.OrderFinancialStatus.CANCELED]: 'Đã hủy',
    [enum_1.OrderFinancialStatus.NOT_PAID]: 'Chưa thanh toán',
    [enum_1.OrderFinancialStatus.PAID]: 'Đã thanh toán',
    [enum_1.OrderFinancialStatus.PARTIALLY_PAID]: 'Thanh toán một phần',
    [enum_1.OrderFinancialStatus.PARTIALLY_REFUNDED]: 'Hoàn tiền một phần',
    [enum_1.OrderFinancialStatus.PENDING]: 'Chờ xử lý',
    [enum_1.OrderFinancialStatus.REFUNDED]: 'Đã hoàn tiền',
};
exports.idFieldDataMapping = [
    {
        key: 'address_id',
        set: new Set(),
        index: elastic_index_1.ELASTIC_INDEX.PARTNER_ADDRESS,
        isShopId: true,
    },
    {
        key: 'shipping_method_id',
        set: new Set(),
        index: elastic_index_1.ELASTIC_INDEX.SHIPPING_METHOD,
        isShopId: false,
    },
    {
        key: 'branch_id',
        set: new Set(),
        index: elastic_index_1.ELASTIC_INDEX.BRANCH,
        isShopId: true,
    },
    {
        key: 'sale_channel_id',
        set: new Set(),
        index: elastic_index_1.ELASTIC_INDEX.SALES_CHANNEL,
        isShopId: false,
    },
    {
        key: 'price_book_id',
        set: new Set(),
        index: elastic_index_1.ELASTIC_INDEX.PRICEBOOK,
        isShopId: true,
    },
    {
        key: 'partner_id',
        set: new Set(),
        index: elastic_index_1.ELASTIC_INDEX.PARTNER,
        fieldFilter: 'uuid',
        isShopId: true,
    },
    {
        key: 'warehouse_id',
        set: new Set(),
        index: elastic_index_1.ELASTIC_INDEX.WAREHOUSE,
        isShopId: true,
    },
    { key: 'staff_id', set: new Set(), index: elastic_index_1.ELASTIC_INDEX.STAFF },
];
//# sourceMappingURL=order.js.map