"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WALLET_SEND_OTP_ACTION_ENUM = void 0;
var WALLET_SEND_OTP_ACTION_ENUM;
(function (WALLET_SEND_OTP_ACTION_ENUM) {
    WALLET_SEND_OTP_ACTION_ENUM["CREATE_WALLET"] = "CREATE_WALLET";
    WALLET_SEND_OTP_ACTION_ENUM["ORDER_VERIFY"] = "ORDER_VERIFY";
})(WALLET_SEND_OTP_ACTION_ENUM || (exports.WALLET_SEND_OTP_ACTION_ENUM = WALLET_SEND_OTP_ACTION_ENUM = {}));
//# sourceMappingURL=wallet.js.map