"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FULFILLMENT_REQUEST_STATUS = exports.FULFILLMENT_ORDER_STATUS = void 0;
var FULFILLMENT_ORDER_STATUS;
(function (FULFILLMENT_ORDER_STATUS) {
    FULFILLMENT_ORDER_STATUS["OPEN"] = "open";
    FULFILLMENT_ORDER_STATUS["IN_PROGRESS"] = "in_progress";
    FULFILLMENT_ORDER_STATUS["SCHEDULED"] = "scheduled";
    FULFILLMENT_ORDER_STATUS["CANCELLED"] = "cancelled";
    FULFILLMENT_ORDER_STATUS["ON_HOLD"] = "on_hold";
    FULFILLMENT_ORDER_STATUS["INCOMPLETE"] = "incomplete";
    FULFILLMENT_ORDER_STATUS["CLOSED"] = "closed";
})(FULFILLMENT_ORDER_STATUS || (exports.FULFILLMENT_ORDER_STATUS = FULFILLMENT_ORDER_STATUS = {}));
var FULFILLMENT_REQUEST_STATUS;
(function (FULFILLMENT_REQUEST_STATUS) {
    FULFILLMENT_REQUEST_STATUS["UNSUBMITTED"] = "unsubmitted";
    FULFILLMENT_REQUEST_STATUS["SUBMITTED"] = "submitted";
    FULFILLMENT_REQUEST_STATUS["ACCEPTED"] = "accepted";
    FULFILLMENT_REQUEST_STATUS["REJECTED"] = "rejected";
    FULFILLMENT_REQUEST_STATUS["CANCELLATION_REQUESTED"] = "cancellation_requested";
    FULFILLMENT_REQUEST_STATUS["CANCELLATION_ACCEPTED"] = "cancellation_accepted";
    FULFILLMENT_REQUEST_STATUS["CANCELLATION_REJECTED"] = "cancellation_rejected";
    FULFILLMENT_REQUEST_STATUS["CLOSED"] = "closed";
})(FULFILLMENT_REQUEST_STATUS || (exports.FULFILLMENT_REQUEST_STATUS = FULFILLMENT_REQUEST_STATUS = {}));
//# sourceMappingURL=fulfillment-order.state.js.map