"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WEBHOOK_PROVIDER_SHIPPING_ENUM = void 0;
var WEBHOOK_PROVIDER_SHIPPING_ENUM;
(function (WEBHOOK_PROVIDER_SHIPPING_ENUM) {
    WEBHOOK_PROVIDER_SHIPPING_ENUM["GHN"] = "ghn";
    WEBHOOK_PROVIDER_SHIPPING_ENUM["GHTK"] = "ghtk";
    WEBHOOK_PROVIDER_SHIPPING_ENUM["AHAMOVE"] = "ahamove";
})(WEBHOOK_PROVIDER_SHIPPING_ENUM || (exports.WEBHOOK_PROVIDER_SHIPPING_ENUM = WEBHOOK_PROVIDER_SHIPPING_ENUM = {}));
//# sourceMappingURL=webhook.state.js.map