export * from './itheme-category';
export * from './itheme';
export * from './iwebsite';
export * from './idocument';
export * from './itemplate';
export * from './cms.icategory';
export * from './ipage';
export * from './ipost';
export * from './imenu';
export declare const THEME_CATEGORY_ENTITY_NAME = "CMSThemeCategoryEntity";
export declare const THEME_ENTITY_NAME = "CMSThemeEntity";
export declare const THEME_TAG_ENTITY_NAME = "CMSThemeTagEntity";
export declare const WEBSITE_ENTITY_NAME = "CMSWebsiteEntity";
export declare const DOCUMENT_ENTITY_NAME = "CMSDocumentEntity";
export declare const TEMPLATE_ENTITY_NAME = "CMSTemplateEntity";
export declare const CMS_CATEGORY_ENTITY_NAME = "CMSCategoryEntity";
export declare const CMS_PAGE_ENTITY_NAME = "CMSPageEntity";
export declare const CMS_POST_ENTITY_NAME = "CMSPostEntity";
export declare const CMS_TAG_ENTITY_NAME = "CMSTagEntity";
export declare const CMS_MENU_ENTITY_NAME = "CMSMenuEntity";
