"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ORDER_RECONCILIATION_ENUM = exports.PAYMENT_METHOD = exports.PAYMENT_RECONCILIATION_STATUS = exports.PAYMENT_TYPE = exports.TRANSACTION_RECONCILIATION_STATUS_ENUM = exports.RECONCILIATION_STATUS_ENUM = exports.ADMIN_RECONCILIATION_STATUS_ENUM = void 0;
var ADMIN_RECONCILIATION_STATUS_ENUM;
(function (ADMIN_RECONCILIATION_STATUS_ENUM) {
    ADMIN_RECONCILIATION_STATUS_ENUM["OPEN"] = "open";
    ADMIN_RECONCILIATION_STATUS_ENUM["CHECKING"] = "checking";
    ADMIN_RECONCILIATION_STATUS_ENUM["DONE"] = "done";
    ADMIN_RECONCILIATION_STATUS_ENUM["CANCELLED"] = "cancelled";
})(ADMIN_RECONCILIATION_STATUS_ENUM || (exports.ADMIN_RECONCILIATION_STATUS_ENUM = ADMIN_RECONCILIATION_STATUS_ENUM = {}));
var RECONCILIATION_STATUS_ENUM;
(function (RECONCILIATION_STATUS_ENUM) {
    RECONCILIATION_STATUS_ENUM["OPEN"] = "open";
    RECONCILIATION_STATUS_ENUM["CHECKING"] = "checking";
    RECONCILIATION_STATUS_ENUM["DONE"] = "done";
    RECONCILIATION_STATUS_ENUM["CANCELLED"] = "cancelled";
})(RECONCILIATION_STATUS_ENUM || (exports.RECONCILIATION_STATUS_ENUM = RECONCILIATION_STATUS_ENUM = {}));
var TRANSACTION_RECONCILIATION_STATUS_ENUM;
(function (TRANSACTION_RECONCILIATION_STATUS_ENUM) {
    TRANSACTION_RECONCILIATION_STATUS_ENUM["WAITING"] = "waiting";
    TRANSACTION_RECONCILIATION_STATUS_ENUM["PROCESSING"] = "processing";
    TRANSACTION_RECONCILIATION_STATUS_ENUM["DONE"] = "done";
})(TRANSACTION_RECONCILIATION_STATUS_ENUM || (exports.TRANSACTION_RECONCILIATION_STATUS_ENUM = TRANSACTION_RECONCILIATION_STATUS_ENUM = {}));
var PAYMENT_TYPE;
(function (PAYMENT_TYPE) {
    PAYMENT_TYPE["RECEIPT"] = "receipt";
})(PAYMENT_TYPE || (exports.PAYMENT_TYPE = PAYMENT_TYPE = {}));
var PAYMENT_RECONCILIATION_STATUS;
(function (PAYMENT_RECONCILIATION_STATUS) {
    PAYMENT_RECONCILIATION_STATUS["OPEN"] = "open";
    PAYMENT_RECONCILIATION_STATUS["PROCESSING"] = "processing";
    PAYMENT_RECONCILIATION_STATUS["PROCEED"] = "proceed";
    PAYMENT_RECONCILIATION_STATUS["SUCCESS"] = "success";
    PAYMENT_RECONCILIATION_STATUS["ERROR"] = "error";
    PAYMENT_RECONCILIATION_STATUS["CANCEL"] = "cancel";
})(PAYMENT_RECONCILIATION_STATUS || (exports.PAYMENT_RECONCILIATION_STATUS = PAYMENT_RECONCILIATION_STATUS = {}));
var PAYMENT_METHOD;
(function (PAYMENT_METHOD) {
    PAYMENT_METHOD["CASH"] = "cash";
    PAYMENT_METHOD["TRANSFER"] = "transfer";
    PAYMENT_METHOD["OTHER"] = "other";
})(PAYMENT_METHOD || (exports.PAYMENT_METHOD = PAYMENT_METHOD = {}));
var ORDER_RECONCILIATION_ENUM;
(function (ORDER_RECONCILIATION_ENUM) {
    ORDER_RECONCILIATION_ENUM["WAITING"] = "waiting";
    ORDER_RECONCILIATION_ENUM["CHECKED"] = "checked";
})(ORDER_RECONCILIATION_ENUM || (exports.ORDER_RECONCILIATION_ENUM = ORDER_RECONCILIATION_ENUM = {}));
//# sourceMappingURL=reconciliation.js.map