"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PACKAGE_ADDITION_TARGET_ENUM = exports.PACKAGE_ADDITION_TYPE_ENUM = exports.PACKAGE_LEVEL_SUPPORT_ENUM = void 0;
var PACKAGE_LEVEL_SUPPORT_ENUM;
(function (PACKAGE_LEVEL_SUPPORT_ENUM) {
    PACKAGE_LEVEL_SUPPORT_ENUM["TRIAL"] = "trial";
    PACKAGE_LEVEL_SUPPORT_ENUM["SUPPORT"] = "support";
    PACKAGE_LEVEL_SUPPORT_ENUM["PRO"] = "pro";
    PACKAGE_LEVEL_SUPPORT_ENUM["PREMIUM"] = "premium";
    PACKAGE_LEVEL_SUPPORT_ENUM["ELITE"] = "elite";
    PACKAGE_LEVEL_SUPPORT_ENUM["LUXURY"] = "luxury";
})(PACKAGE_LEVEL_SUPPORT_ENUM || (exports.PACKAGE_LEVEL_SUPPORT_ENUM = PACKAGE_LEVEL_SUPPORT_ENUM = {}));
var PACKAGE_ADDITION_TYPE_ENUM;
(function (PACKAGE_ADDITION_TYPE_ENUM) {
    PACKAGE_ADDITION_TYPE_ENUM["REPLACE_DURATION"] = "replace_duration";
    PACKAGE_ADDITION_TYPE_ENUM["ADD_DURATION"] = "add_duration";
    PACKAGE_ADDITION_TYPE_ENUM["ADD_BRANCH"] = "add_branch";
    PACKAGE_ADDITION_TYPE_ENUM["ADD_USER"] = "add_user";
})(PACKAGE_ADDITION_TYPE_ENUM || (exports.PACKAGE_ADDITION_TYPE_ENUM = PACKAGE_ADDITION_TYPE_ENUM = {}));
var PACKAGE_ADDITION_TARGET_ENUM;
(function (PACKAGE_ADDITION_TARGET_ENUM) {
    PACKAGE_ADDITION_TARGET_ENUM["DAY"] = "day";
    PACKAGE_ADDITION_TARGET_ENUM["MONTH"] = "month";
    PACKAGE_ADDITION_TARGET_ENUM["YEAR"] = "year";
    PACKAGE_ADDITION_TARGET_ENUM["USER"] = "user";
    PACKAGE_ADDITION_TARGET_ENUM["BRANCH"] = "branch";
})(PACKAGE_ADDITION_TARGET_ENUM || (exports.PACKAGE_ADDITION_TARGET_ENUM = PACKAGE_ADDITION_TARGET_ENUM = {}));
//# sourceMappingURL=package.state.js.map