export enum PromotionTargetType {
	BUSINESS_TYPE = 'BUSINESS_TYPE',
	PACKAGE = 'PACKAGE',
	APPLICATION = 'APPLICATION',
	CUSTOMER = 'CUSTOMER',
	SHOP = 'SHOP',
}

export enum PromotionRewardType {
	DISCOUNT = 'DISCOUNT',
	EXTEND_TIME = 'EXTEND_TIME',
	ADD_FEATURE = 'ADD_FEATURE',
	ADD_EMPLOYEE = 'ADD_EMPLOYEE',
	ADD_BRANCH = 'ADD_BRANCH',
}

export enum PromotionRewardUnit {
	PERCENT = 'PERCENT',
	FIXED_AMOUNT = 'FIXED_AMOUNT',
	DAYS = 'DAYS',
	FEATURE = 'FEATURE',
	NUMBER = 'NUMBER',
}
