"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RECEIPT_AUTO_TRANSITION_RULES = exports.RECEIPT_STATUS_WORKFLOW = exports.RECEIPT_PROCESSING_STATUS_ENUM = exports.RECEIPT_PAYMENT_METHOD_ENUM = exports.RECEIPT_TYPE_ENUM = exports.RECEIPT_PAYMENT_STATUS_ENUM = exports.RECEIPT_PRIORITY_ENUM = exports.RECEIPT_LINE_ITEM_TYPE_ENUM = exports.RECEIPT_STATUS_ENUM = exports.RECEIPT_SOURCE_ENUM = exports.RECEIPT_SOURCE_TYPE_ENUM = void 0;
var RECEIPT_SOURCE_TYPE_ENUM;
(function (RECEIPT_SOURCE_TYPE_ENUM) {
    RECEIPT_SOURCE_TYPE_ENUM["AUTOMATIC"] = "automatic";
    RECEIPT_SOURCE_TYPE_ENUM["MANUAL"] = "manual";
})(RECEIPT_SOURCE_TYPE_ENUM || (exports.RECEIPT_SOURCE_TYPE_ENUM = RECEIPT_SOURCE_TYPE_ENUM = {}));
var RECEIPT_SOURCE_ENUM;
(function (RECEIPT_SOURCE_ENUM) {
    RECEIPT_SOURCE_ENUM["ADMIN"] = "admin";
    RECEIPT_SOURCE_ENUM["BO_SHOP"] = "bo_shop";
})(RECEIPT_SOURCE_ENUM || (exports.RECEIPT_SOURCE_ENUM = RECEIPT_SOURCE_ENUM = {}));
var RECEIPT_STATUS_ENUM;
(function (RECEIPT_STATUS_ENUM) {
    RECEIPT_STATUS_ENUM["DRAFT"] = "draft";
    RECEIPT_STATUS_ENUM["OPEN"] = "open";
    RECEIPT_STATUS_ENUM["PENDING_PAYMENT"] = "pending_payment";
    RECEIPT_STATUS_ENUM["PROCESSING"] = "processing";
    RECEIPT_STATUS_ENUM["CONFIRMED"] = "confirmed";
    RECEIPT_STATUS_ENUM["COMPLETED"] = "completed";
    RECEIPT_STATUS_ENUM["PARTIALLY_REFUNDED"] = "partially_refunded";
    RECEIPT_STATUS_ENUM["FULLY_REFUNDED"] = "fully_refunded";
    RECEIPT_STATUS_ENUM["CANCELLED"] = "cancelled";
    RECEIPT_STATUS_ENUM["EXPIRED"] = "expired";
    RECEIPT_STATUS_ENUM["FAILED"] = "failed";
    RECEIPT_STATUS_ENUM["SUSPENDED"] = "suspended";
})(RECEIPT_STATUS_ENUM || (exports.RECEIPT_STATUS_ENUM = RECEIPT_STATUS_ENUM = {}));
var RECEIPT_LINE_ITEM_TYPE_ENUM;
(function (RECEIPT_LINE_ITEM_TYPE_ENUM) {
    RECEIPT_LINE_ITEM_TYPE_ENUM["PACKAGE_ADDITION"] = "package_addition";
    RECEIPT_LINE_ITEM_TYPE_ENUM["APP_PLAN"] = "app_plan";
    RECEIPT_LINE_ITEM_TYPE_ENUM["STAFF_QUANTITY"] = "staff_quantity";
    RECEIPT_LINE_ITEM_TYPE_ENUM["BRANCH_QUANTITY"] = "branch_quantity";
    RECEIPT_LINE_ITEM_TYPE_ENUM["THEME"] = "theme";
    RECEIPT_LINE_ITEM_TYPE_ENUM["DOMAIN"] = "domain";
})(RECEIPT_LINE_ITEM_TYPE_ENUM || (exports.RECEIPT_LINE_ITEM_TYPE_ENUM = RECEIPT_LINE_ITEM_TYPE_ENUM = {}));
var RECEIPT_PRIORITY_ENUM;
(function (RECEIPT_PRIORITY_ENUM) {
    RECEIPT_PRIORITY_ENUM["URGENT"] = "urgent";
    RECEIPT_PRIORITY_ENUM["HIGH"] = "high";
    RECEIPT_PRIORITY_ENUM["MEDIUM"] = "medium";
    RECEIPT_PRIORITY_ENUM["LOW"] = "low";
})(RECEIPT_PRIORITY_ENUM || (exports.RECEIPT_PRIORITY_ENUM = RECEIPT_PRIORITY_ENUM = {}));
var RECEIPT_PAYMENT_STATUS_ENUM;
(function (RECEIPT_PAYMENT_STATUS_ENUM) {
    RECEIPT_PAYMENT_STATUS_ENUM["UNPAID"] = "unpaid";
    RECEIPT_PAYMENT_STATUS_ENUM["PARTIAL"] = "partial";
    RECEIPT_PAYMENT_STATUS_ENUM["PAID"] = "paid";
    RECEIPT_PAYMENT_STATUS_ENUM["OVERPAID"] = "overpaid";
    RECEIPT_PAYMENT_STATUS_ENUM["REFUNDED"] = "refunded";
})(RECEIPT_PAYMENT_STATUS_ENUM || (exports.RECEIPT_PAYMENT_STATUS_ENUM = RECEIPT_PAYMENT_STATUS_ENUM = {}));
var RECEIPT_TYPE_ENUM;
(function (RECEIPT_TYPE_ENUM) {
    RECEIPT_TYPE_ENUM["SUBSCRIPTION"] = "subscription";
    RECEIPT_TYPE_ENUM["RENEWAL"] = "renewal";
    RECEIPT_TYPE_ENUM["UPGRADE"] = "upgrade";
    RECEIPT_TYPE_ENUM["ADDON"] = "addon";
    RECEIPT_TYPE_ENUM["REFUND"] = "refund";
    RECEIPT_TYPE_ENUM["ADJUSTMENT"] = "adjustment";
    RECEIPT_TYPE_ENUM["DIGITAL_PURCHASE"] = "digital_purchase";
})(RECEIPT_TYPE_ENUM || (exports.RECEIPT_TYPE_ENUM = RECEIPT_TYPE_ENUM = {}));
var RECEIPT_PAYMENT_METHOD_ENUM;
(function (RECEIPT_PAYMENT_METHOD_ENUM) {
    RECEIPT_PAYMENT_METHOD_ENUM["CREDIT_CARD"] = "credit_card";
    RECEIPT_PAYMENT_METHOD_ENUM["BANK_TRANSFER"] = "bank_transfer";
    RECEIPT_PAYMENT_METHOD_ENUM["E_WALLET"] = "e_wallet";
    RECEIPT_PAYMENT_METHOD_ENUM["CASH"] = "cash";
    RECEIPT_PAYMENT_METHOD_ENUM["CRYPTO"] = "crypto";
    RECEIPT_PAYMENT_METHOD_ENUM["VOUCHER"] = "voucher";
    RECEIPT_PAYMENT_METHOD_ENUM["CREDIT"] = "credit";
})(RECEIPT_PAYMENT_METHOD_ENUM || (exports.RECEIPT_PAYMENT_METHOD_ENUM = RECEIPT_PAYMENT_METHOD_ENUM = {}));
var RECEIPT_PROCESSING_STATUS_ENUM;
(function (RECEIPT_PROCESSING_STATUS_ENUM) {
    RECEIPT_PROCESSING_STATUS_ENUM["QUEUE"] = "queue";
    RECEIPT_PROCESSING_STATUS_ENUM["PROCESSING"] = "processing";
    RECEIPT_PROCESSING_STATUS_ENUM["AWAITING_APPROVAL"] = "awaiting_approval";
    RECEIPT_PROCESSING_STATUS_ENUM["APPROVED"] = "approved";
    RECEIPT_PROCESSING_STATUS_ENUM["REJECTED"] = "rejected";
    RECEIPT_PROCESSING_STATUS_ENUM["COMPLETED"] = "completed";
})(RECEIPT_PROCESSING_STATUS_ENUM || (exports.RECEIPT_PROCESSING_STATUS_ENUM = RECEIPT_PROCESSING_STATUS_ENUM = {}));
exports.RECEIPT_STATUS_WORKFLOW = {
    BASIC_FLOW: [
        RECEIPT_STATUS_ENUM.DRAFT,
        RECEIPT_STATUS_ENUM.OPEN,
        RECEIPT_STATUS_ENUM.PENDING_PAYMENT,
        RECEIPT_STATUS_ENUM.PROCESSING,
        RECEIPT_STATUS_ENUM.CONFIRMED,
        RECEIPT_STATUS_ENUM.COMPLETED,
    ],
    REFUND_FLOW: [
        RECEIPT_STATUS_ENUM.COMPLETED,
        RECEIPT_STATUS_ENUM.PARTIALLY_REFUNDED,
        RECEIPT_STATUS_ENUM.FULLY_REFUNDED,
    ],
    FINAL_STATES: [
        RECEIPT_STATUS_ENUM.COMPLETED,
        RECEIPT_STATUS_ENUM.FULLY_REFUNDED,
        RECEIPT_STATUS_ENUM.CANCELLED,
        RECEIPT_STATUS_ENUM.EXPIRED,
        RECEIPT_STATUS_ENUM.FAILED,
    ],
    PROCESSABLE_STATES: [
        RECEIPT_STATUS_ENUM.OPEN,
        RECEIPT_STATUS_ENUM.PENDING_PAYMENT,
        RECEIPT_STATUS_ENUM.PROCESSING,
        RECEIPT_STATUS_ENUM.CONFIRMED,
    ],
};
exports.RECEIPT_AUTO_TRANSITION_RULES = {
    AUTO_EXPIRE_DAYS: 30,
    AUTO_PROCESS_ON_PAYMENT: true,
    AUTO_COMPLETE_ON_FULL_PAYMENT: true,
};
//# sourceMappingURL=receipt.js.map