"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RECEIPT_LINE_ITEM_TYPE_ENUM = exports.RECEIPT_STATUS_ENUM = exports.RECEIPT_SOURCE_ENUM = exports.RECEIPT_SOURCE_TYPE_ENUM = void 0;
var RECEIPT_SOURCE_TYPE_ENUM;
(function (RECEIPT_SOURCE_TYPE_ENUM) {
    RECEIPT_SOURCE_TYPE_ENUM["AUTOMATIC"] = "automatic";
    RECEIPT_SOURCE_TYPE_ENUM["MANUAL"] = "manual";
})(RECEIPT_SOURCE_TYPE_ENUM || (exports.RECEIPT_SOURCE_TYPE_ENUM = RECEIPT_SOURCE_TYPE_ENUM = {}));
var RECEIPT_SOURCE_ENUM;
(function (RECEIPT_SOURCE_ENUM) {
    RECEIPT_SOURCE_ENUM["ADMIN"] = "admin";
    RECEIPT_SOURCE_ENUM["BO_SHOP"] = "bo_shop";
})(RECEIPT_SOURCE_ENUM || (exports.RECEIPT_SOURCE_ENUM = RECEIPT_SOURCE_ENUM = {}));
var RECEIPT_STATUS_ENUM;
(function (RECEIPT_STATUS_ENUM) {
    RECEIPT_STATUS_ENUM["OPEN"] = "open";
    RECEIPT_STATUS_ENUM["COMPLETED"] = "completed";
    RECEIPT_STATUS_ENUM["CANCELLED"] = "cancelled";
})(RECEIPT_STATUS_ENUM || (exports.RECEIPT_STATUS_ENUM = RECEIPT_STATUS_ENUM = {}));
var RECEIPT_LINE_ITEM_TYPE_ENUM;
(function (RECEIPT_LINE_ITEM_TYPE_ENUM) {
    RECEIPT_LINE_ITEM_TYPE_ENUM["PACKAGE_ADDITION"] = "package_addition";
    RECEIPT_LINE_ITEM_TYPE_ENUM["APP_PLAN"] = "app_plan";
})(RECEIPT_LINE_ITEM_TYPE_ENUM || (exports.RECEIPT_LINE_ITEM_TYPE_ENUM = RECEIPT_LINE_ITEM_TYPE_ENUM = {}));
//# sourceMappingURL=receipt.js.map