"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AIImageIdeogramStyleType = exports.AIImageRenderingSpeed = exports.AIImageOperation = exports.AIImageProvider = exports.AIImageQuality = exports.AIImageStyle = exports.AIImageContentType = exports.AIContentTransactionStatus = exports.AIContentTransactionType = exports.AIContentTone = exports.AIContentJobStatus = exports.AIContentType = exports.AIContentIndustry = void 0;
var AIContentIndustry;
(function (AIContentIndustry) {
    AIContentIndustry["GENERAL"] = "general";
    AIContentIndustry["RETAIL"] = "retail";
    AIContentIndustry["FNB"] = "fnb";
    AIContentIndustry["HOTEL"] = "hotel";
    AIContentIndustry["CLINIC"] = "clinic";
    AIContentIndustry["WELLNESS"] = "wellness";
    AIContentIndustry["SERVICE"] = "service";
})(AIContentIndustry || (exports.AIContentIndustry = AIContentIndustry = {}));
var AIContentType;
(function (AIContentType) {
    AIContentType["PRODUCT_SHORT_DESCRIPTION"] = "product_short_description";
    AIContentType["PRODUCT_SEO_ARTICLE"] = "product_seo_article";
    AIContentType["CMS_NEWS_ARTICLE"] = "cms_news_article";
    AIContentType["CMS_BLOG_POST"] = "cms_blog_post";
    AIContentType["SHORT_DESCRIPTION"] = "short_description";
    AIContentType["SEO_ARTICLE"] = "seo_article";
    AIContentType["BLOG_POST"] = "blog_post";
    AIContentType["NEWS_ARTICLE"] = "news_article";
    AIContentType["FAQ_CONTENT"] = "faq_content";
    AIContentType["ABOUT_PAGE"] = "about_page";
    AIContentType["PROMOTION_COPY"] = "promotion_copy";
    AIContentType["REVIEW_RESPONSE"] = "review_response";
    AIContentType["FNB_MENU_ITEM"] = "fnb_menu_item";
    AIContentType["FNB_RESTAURANT_PROFILE"] = "fnb_restaurant_profile";
    AIContentType["FNB_DAILY_SPECIAL"] = "fnb_daily_special";
    AIContentType["FNB_FOOD_PAIRING"] = "fnb_food_pairing";
    AIContentType["FNB_EVENT_CATERING"] = "fnb_event_catering";
    AIContentType["RETAIL_PRODUCT_DESC"] = "retail_product_desc";
    AIContentType["RETAIL_CATEGORY_DESC"] = "retail_category_desc";
    AIContentType["RETAIL_COLLECTION_STORY"] = "retail_collection_story";
    AIContentType["RETAIL_GIFT_GUIDE"] = "retail_gift_guide";
    AIContentType["RETAIL_SIZE_GUIDE"] = "retail_size_guide";
    AIContentType["RETAIL_MATERIAL_DESC"] = "retail_material_desc";
    AIContentType["RETAIL_COMPARISON"] = "retail_comparison";
    AIContentType["FNB_DRINK_MENU"] = "fnb_drink_menu";
    AIContentType["FNB_SEASONAL_MENU"] = "fnb_seasonal_menu";
    AIContentType["FNB_CHEF_STORY"] = "fnb_chef_story";
    AIContentType["FNB_DELIVERY_DESC"] = "fnb_delivery_desc";
    AIContentType["FNB_BRANCH_INTRO"] = "fnb_branch_intro";
    AIContentType["RETAIL_FLASH_SALE"] = "retail_flash_sale";
    AIContentType["RETAIL_LOYALTY_PROGRAM"] = "retail_loyalty_program";
    AIContentType["RETAIL_WHOLESALE_CATALOG"] = "retail_wholesale_catalog";
    AIContentType["HOTEL_ROOM_DESC"] = "hotel_room_desc";
    AIContentType["HOTEL_FACILITY_TOUR"] = "hotel_facility_tour";
    AIContentType["HOTEL_PACKAGE_DESC"] = "hotel_package_desc";
    AIContentType["HOTEL_DINING_DESC"] = "hotel_dining_desc";
    AIContentType["HOTEL_EVENT_VENUE"] = "hotel_event_venue";
    AIContentType["HOTEL_LOCAL_GUIDE"] = "hotel_local_guide";
    AIContentType["HOTEL_GUEST_EXPERIENCE"] = "hotel_guest_experience";
    AIContentType["HOTEL_SEASONAL_OFFER"] = "hotel_seasonal_offer";
    AIContentType["HOTEL_AMENITY_DESC"] = "hotel_amenity_desc";
    AIContentType["HOTEL_LOYALTY_PROGRAM"] = "hotel_loyalty_program";
    AIContentType["CLINIC_SERVICE_DESC"] = "clinic_service_desc";
    AIContentType["CLINIC_DOCTOR_PROFILE"] = "clinic_doctor_profile";
    AIContentType["CLINIC_TREATMENT_GUIDE"] = "clinic_treatment_guide";
    AIContentType["CLINIC_HEALTH_TIPS"] = "clinic_health_tips";
    AIContentType["CLINIC_PATIENT_FAQ"] = "clinic_patient_faq";
    AIContentType["CLINIC_FACILITY_DESC"] = "clinic_facility_desc";
    AIContentType["CLINIC_INSURANCE_INFO"] = "clinic_insurance_info";
    AIContentType["CLINIC_SPECIALTY_DESC"] = "clinic_specialty_desc";
    AIContentType["CLINIC_TESTIMONIAL"] = "clinic_testimonial";
    AIContentType["CLINIC_WELLNESS_PROGRAM"] = "clinic_wellness_program";
    AIContentType["WELLNESS_SERVICE_DESC"] = "wellness_service_desc";
    AIContentType["WELLNESS_THERAPIST_PROFILE"] = "wellness_therapist_profile";
    AIContentType["WELLNESS_MEMBERSHIP_DESC"] = "wellness_membership_desc";
    AIContentType["WELLNESS_HEALTH_TIPS"] = "wellness_health_tips";
    AIContentType["WELLNESS_TREATMENT_DESC"] = "wellness_treatment_desc";
    AIContentType["WELLNESS_CLASS_SCHEDULE"] = "wellness_class_schedule";
    AIContentType["WELLNESS_PACKAGE_DESC"] = "wellness_package_desc";
    AIContentType["WELLNESS_FACILITY_TOUR"] = "wellness_facility_tour";
    AIContentType["WELLNESS_TRANSFORMATION"] = "wellness_transformation";
    AIContentType["WELLNESS_SEASONAL_PROMO"] = "wellness_seasonal_promo";
    AIContentType["SERVICE_VENUE_DESC"] = "service_venue_desc";
    AIContentType["SERVICE_PRICING_TABLE"] = "service_pricing_table";
    AIContentType["SERVICE_BOOKING_DESC"] = "service_booking_desc";
    AIContentType["SERVICE_EVENT_PACKAGE"] = "service_event_package";
    AIContentType["SERVICE_MEMBERSHIP_DESC"] = "service_membership_desc";
    AIContentType["SERVICE_FACILITY_DESC"] = "service_facility_desc";
    AIContentType["SERVICE_TOURNAMENT_DESC"] = "service_tournament_desc";
    AIContentType["SERVICE_GROUP_PACKAGE"] = "service_group_package";
    AIContentType["SERVICE_CLASS_DESC"] = "service_class_desc";
    AIContentType["SERVICE_LOYALTY_PROGRAM"] = "service_loyalty_program";
    AIContentType["PRODUCT_IMAGE"] = "product_image";
    AIContentType["BLOG_THUMBNAIL"] = "blog_thumbnail";
    AIContentType["MARKETING_BANNER"] = "marketing_banner";
})(AIContentType || (exports.AIContentType = AIContentType = {}));
var AIContentJobStatus;
(function (AIContentJobStatus) {
    AIContentJobStatus["PENDING"] = "pending";
    AIContentJobStatus["PROCESSING"] = "processing";
    AIContentJobStatus["COMPLETED"] = "completed";
    AIContentJobStatus["FAILED"] = "failed";
})(AIContentJobStatus || (exports.AIContentJobStatus = AIContentJobStatus = {}));
var AIContentTone;
(function (AIContentTone) {
    AIContentTone["PROFESSIONAL"] = "professional";
    AIContentTone["FRIENDLY"] = "friendly";
    AIContentTone["FORMAL"] = "formal";
    AIContentTone["CASUAL"] = "casual";
    AIContentTone["LUXURY"] = "luxury";
    AIContentTone["APPETIZING"] = "appetizing";
    AIContentTone["RELAXING"] = "relaxing";
    AIContentTone["ENERGETIC"] = "energetic";
    AIContentTone["ELEGANT"] = "elegant";
    AIContentTone["WARM"] = "warm";
    AIContentTone["CLINICAL"] = "clinical";
    AIContentTone["SPORTY"] = "sporty";
    AIContentTone["SERENE"] = "serene";
})(AIContentTone || (exports.AIContentTone = AIContentTone = {}));
var AIContentTransactionType;
(function (AIContentTransactionType) {
    AIContentTransactionType["DEBIT"] = "debit";
    AIContentTransactionType["CREDIT"] = "credit";
    AIContentTransactionType["REFUND"] = "refund";
})(AIContentTransactionType || (exports.AIContentTransactionType = AIContentTransactionType = {}));
var AIContentTransactionStatus;
(function (AIContentTransactionStatus) {
    AIContentTransactionStatus["PENDING"] = "pending";
    AIContentTransactionStatus["COMPLETED"] = "completed";
    AIContentTransactionStatus["FAILED"] = "failed";
})(AIContentTransactionStatus || (exports.AIContentTransactionStatus = AIContentTransactionStatus = {}));
var AIImageContentType;
(function (AIImageContentType) {
    AIImageContentType["PRODUCT_IMAGE"] = "product_image";
    AIImageContentType["BLOG_THUMBNAIL"] = "blog_thumbnail";
    AIImageContentType["MARKETING_BANNER"] = "marketing_banner";
    AIImageContentType["FNB_IMG_FOOD_HERO"] = "fnb_img_food_hero";
    AIImageContentType["FNB_IMG_MENU_DESIGN"] = "fnb_img_menu_design";
    AIImageContentType["FNB_IMG_INTERIOR"] = "fnb_img_interior";
    AIImageContentType["FNB_IMG_DRINK"] = "fnb_img_drink";
    AIImageContentType["FNB_IMG_INGREDIENT"] = "fnb_img_ingredient";
    AIImageContentType["FNB_IMG_SOCIAL_POST"] = "fnb_img_social_post";
    AIImageContentType["FNB_IMG_BANNER"] = "fnb_img_banner";
    AIImageContentType["FNB_IMG_STORY"] = "fnb_img_story";
    AIImageContentType["RETAIL_IMG_PRODUCT"] = "retail_img_product";
    AIImageContentType["RETAIL_IMG_LIFESTYLE"] = "retail_img_lifestyle";
    AIImageContentType["RETAIL_IMG_BANNER"] = "retail_img_banner";
    AIImageContentType["RETAIL_IMG_CATEGORY"] = "retail_img_category";
    AIImageContentType["RETAIL_IMG_COLLECTION"] = "retail_img_collection";
    AIImageContentType["RETAIL_IMG_SOCIAL_POST"] = "retail_img_social_post";
    AIImageContentType["RETAIL_IMG_PACKAGING"] = "retail_img_packaging";
    AIImageContentType["RETAIL_IMG_MODEL"] = "retail_img_model";
    AIImageContentType["HOTEL_IMG_ROOM"] = "hotel_img_room";
    AIImageContentType["HOTEL_IMG_EXTERIOR"] = "hotel_img_exterior";
    AIImageContentType["HOTEL_IMG_POOL"] = "hotel_img_pool";
    AIImageContentType["HOTEL_IMG_DINING"] = "hotel_img_dining";
    AIImageContentType["HOTEL_IMG_LOBBY"] = "hotel_img_lobby";
    AIImageContentType["HOTEL_IMG_VIEW"] = "hotel_img_view";
    AIImageContentType["HOTEL_IMG_BANNER"] = "hotel_img_banner";
    AIImageContentType["HOTEL_IMG_SOCIAL_POST"] = "hotel_img_social_post";
    AIImageContentType["CLINIC_IMG_FACILITY"] = "clinic_img_facility";
    AIImageContentType["CLINIC_IMG_DOCTOR"] = "clinic_img_doctor";
    AIImageContentType["CLINIC_IMG_EQUIPMENT"] = "clinic_img_equipment";
    AIImageContentType["CLINIC_IMG_TREATMENT"] = "clinic_img_treatment";
    AIImageContentType["CLINIC_IMG_RECEPTION"] = "clinic_img_reception";
    AIImageContentType["CLINIC_IMG_BANNER"] = "clinic_img_banner";
    AIImageContentType["CLINIC_IMG_SOCIAL_POST"] = "clinic_img_social_post";
    AIImageContentType["CLINIC_IMG_INFOGRAPHIC"] = "clinic_img_infographic";
    AIImageContentType["WELLNESS_IMG_SPA_ROOM"] = "wellness_img_spa_room";
    AIImageContentType["WELLNESS_IMG_TREATMENT"] = "wellness_img_treatment";
    AIImageContentType["WELLNESS_IMG_THERAPIST"] = "wellness_img_therapist";
    AIImageContentType["WELLNESS_IMG_AMBIANCE"] = "wellness_img_ambiance";
    AIImageContentType["WELLNESS_IMG_FITNESS"] = "wellness_img_fitness";
    AIImageContentType["WELLNESS_IMG_PRODUCT"] = "wellness_img_product";
    AIImageContentType["WELLNESS_IMG_BANNER"] = "wellness_img_banner";
    AIImageContentType["WELLNESS_IMG_SOCIAL_POST"] = "wellness_img_social_post";
    AIImageContentType["SERVICE_IMG_VENUE"] = "service_img_venue";
    AIImageContentType["SERVICE_IMG_ACTIVITY"] = "service_img_activity";
    AIImageContentType["SERVICE_IMG_EQUIPMENT"] = "service_img_equipment";
    AIImageContentType["SERVICE_IMG_GROUP"] = "service_img_group";
    AIImageContentType["SERVICE_IMG_INTERIOR"] = "service_img_interior";
    AIImageContentType["SERVICE_IMG_EXTERIOR"] = "service_img_exterior";
    AIImageContentType["SERVICE_IMG_BANNER"] = "service_img_banner";
    AIImageContentType["SERVICE_IMG_SOCIAL_POST"] = "service_img_social_post";
})(AIImageContentType || (exports.AIImageContentType = AIImageContentType = {}));
var AIImageStyle;
(function (AIImageStyle) {
    AIImageStyle["LIFESTYLE"] = "lifestyle";
    AIImageStyle["STUDIO"] = "studio";
    AIImageStyle["MINIMAL"] = "minimal";
    AIImageStyle["CREATIVE"] = "creative";
})(AIImageStyle || (exports.AIImageStyle = AIImageStyle = {}));
var AIImageQuality;
(function (AIImageQuality) {
    AIImageQuality["STANDARD"] = "standard";
    AIImageQuality["HD"] = "hd";
})(AIImageQuality || (exports.AIImageQuality = AIImageQuality = {}));
var AIImageProvider;
(function (AIImageProvider) {
    AIImageProvider["IMAGEN"] = "imagen";
    AIImageProvider["FLUX_SCHNELL"] = "flux_schnell";
    AIImageProvider["FLUX_DEV"] = "flux_dev";
    AIImageProvider["IDEOGRAM"] = "ideogram";
})(AIImageProvider || (exports.AIImageProvider = AIImageProvider = {}));
var AIImageOperation;
(function (AIImageOperation) {
    AIImageOperation["GENERATE"] = "generate";
    AIImageOperation["EDIT"] = "edit";
    AIImageOperation["REMIX"] = "remix";
    AIImageOperation["REFRAME"] = "reframe";
})(AIImageOperation || (exports.AIImageOperation = AIImageOperation = {}));
var AIImageRenderingSpeed;
(function (AIImageRenderingSpeed) {
    AIImageRenderingSpeed["TURBO"] = "TURBO";
    AIImageRenderingSpeed["BALANCED"] = "BALANCED";
    AIImageRenderingSpeed["QUALITY"] = "QUALITY";
})(AIImageRenderingSpeed || (exports.AIImageRenderingSpeed = AIImageRenderingSpeed = {}));
var AIImageIdeogramStyleType;
(function (AIImageIdeogramStyleType) {
    AIImageIdeogramStyleType["AUTO"] = "AUTO";
    AIImageIdeogramStyleType["GENERAL"] = "GENERAL";
    AIImageIdeogramStyleType["REALISTIC"] = "REALISTIC";
    AIImageIdeogramStyleType["DESIGN"] = "DESIGN";
    AIImageIdeogramStyleType["FICTION"] = "FICTION";
})(AIImageIdeogramStyleType || (exports.AIImageIdeogramStyleType = AIImageIdeogramStyleType = {}));
//# sourceMappingURL=index.js.map