export declare enum AIContentIndustry {
    GENERAL = "general",
    RETAIL = "retail",
    FNB = "fnb",
    HOTEL = "hotel",
    CLINIC = "clinic",
    WELLNESS = "wellness",
    SERVICE = "service"
}
export declare enum AIContentType {
    PRODUCT_SHORT_DESCRIPTION = "product_short_description",
    PRODUCT_SEO_ARTICLE = "product_seo_article",
    CMS_NEWS_ARTICLE = "cms_news_article",
    CMS_BLOG_POST = "cms_blog_post",
    SHORT_DESCRIPTION = "short_description",
    SEO_ARTICLE = "seo_article",
    BLOG_POST = "blog_post",
    NEWS_ARTICLE = "news_article",
    FAQ_CONTENT = "faq_content",
    ABOUT_PAGE = "about_page",
    PROMOTION_COPY = "promotion_copy",
    REVIEW_RESPONSE = "review_response",
    FNB_MENU_ITEM = "fnb_menu_item",
    FNB_RESTAURANT_PROFILE = "fnb_restaurant_profile",
    FNB_DAILY_SPECIAL = "fnb_daily_special",
    FNB_FOOD_PAIRING = "fnb_food_pairing",
    FNB_EVENT_CATERING = "fnb_event_catering",
    RETAIL_PRODUCT_DESC = "retail_product_desc",
    RETAIL_CATEGORY_DESC = "retail_category_desc",
    RETAIL_COLLECTION_STORY = "retail_collection_story",
    RETAIL_GIFT_GUIDE = "retail_gift_guide",
    RETAIL_SIZE_GUIDE = "retail_size_guide",
    RETAIL_MATERIAL_DESC = "retail_material_desc",
    RETAIL_COMPARISON = "retail_comparison",
    FNB_DRINK_MENU = "fnb_drink_menu",
    FNB_SEASONAL_MENU = "fnb_seasonal_menu",
    FNB_CHEF_STORY = "fnb_chef_story",
    FNB_DELIVERY_DESC = "fnb_delivery_desc",
    FNB_BRANCH_INTRO = "fnb_branch_intro",
    RETAIL_FLASH_SALE = "retail_flash_sale",
    RETAIL_LOYALTY_PROGRAM = "retail_loyalty_program",
    RETAIL_WHOLESALE_CATALOG = "retail_wholesale_catalog",
    HOTEL_ROOM_DESC = "hotel_room_desc",
    HOTEL_FACILITY_TOUR = "hotel_facility_tour",
    HOTEL_PACKAGE_DESC = "hotel_package_desc",
    HOTEL_DINING_DESC = "hotel_dining_desc",
    HOTEL_EVENT_VENUE = "hotel_event_venue",
    HOTEL_LOCAL_GUIDE = "hotel_local_guide",
    HOTEL_GUEST_EXPERIENCE = "hotel_guest_experience",
    HOTEL_SEASONAL_OFFER = "hotel_seasonal_offer",
    HOTEL_AMENITY_DESC = "hotel_amenity_desc",
    HOTEL_LOYALTY_PROGRAM = "hotel_loyalty_program",
    CLINIC_SERVICE_DESC = "clinic_service_desc",
    CLINIC_DOCTOR_PROFILE = "clinic_doctor_profile",
    CLINIC_TREATMENT_GUIDE = "clinic_treatment_guide",
    CLINIC_HEALTH_TIPS = "clinic_health_tips",
    CLINIC_PATIENT_FAQ = "clinic_patient_faq",
    CLINIC_FACILITY_DESC = "clinic_facility_desc",
    CLINIC_INSURANCE_INFO = "clinic_insurance_info",
    CLINIC_SPECIALTY_DESC = "clinic_specialty_desc",
    CLINIC_TESTIMONIAL = "clinic_testimonial",
    CLINIC_WELLNESS_PROGRAM = "clinic_wellness_program",
    WELLNESS_SERVICE_DESC = "wellness_service_desc",
    WELLNESS_THERAPIST_PROFILE = "wellness_therapist_profile",
    WELLNESS_MEMBERSHIP_DESC = "wellness_membership_desc",
    WELLNESS_HEALTH_TIPS = "wellness_health_tips",
    WELLNESS_TREATMENT_DESC = "wellness_treatment_desc",
    WELLNESS_CLASS_SCHEDULE = "wellness_class_schedule",
    WELLNESS_PACKAGE_DESC = "wellness_package_desc",
    WELLNESS_FACILITY_TOUR = "wellness_facility_tour",
    WELLNESS_TRANSFORMATION = "wellness_transformation",
    WELLNESS_SEASONAL_PROMO = "wellness_seasonal_promo",
    SERVICE_VENUE_DESC = "service_venue_desc",
    SERVICE_PRICING_TABLE = "service_pricing_table",
    SERVICE_BOOKING_DESC = "service_booking_desc",
    SERVICE_EVENT_PACKAGE = "service_event_package",
    SERVICE_MEMBERSHIP_DESC = "service_membership_desc",
    SERVICE_FACILITY_DESC = "service_facility_desc",
    SERVICE_TOURNAMENT_DESC = "service_tournament_desc",
    SERVICE_GROUP_PACKAGE = "service_group_package",
    SERVICE_CLASS_DESC = "service_class_desc",
    SERVICE_LOYALTY_PROGRAM = "service_loyalty_program",
    PRODUCT_IMAGE = "product_image",
    BLOG_THUMBNAIL = "blog_thumbnail",
    MARKETING_BANNER = "marketing_banner"
}
export declare enum AIContentJobStatus {
    PENDING = "pending",
    PROCESSING = "processing",
    COMPLETED = "completed",
    FAILED = "failed"
}
export declare enum AIContentTone {
    PROFESSIONAL = "professional",
    FRIENDLY = "friendly",
    FORMAL = "formal",
    CASUAL = "casual",
    LUXURY = "luxury",
    APPETIZING = "appetizing",
    RELAXING = "relaxing",
    ENERGETIC = "energetic",
    ELEGANT = "elegant",
    WARM = "warm",
    CLINICAL = "clinical",
    SPORTY = "sporty",
    SERENE = "serene"
}
export declare enum AIContentTransactionType {
    DEBIT = "debit",
    CREDIT = "credit",
    REFUND = "refund"
}
export declare enum AIContentTransactionStatus {
    PENDING = "pending",
    COMPLETED = "completed",
    FAILED = "failed"
}
export declare enum AIImageContentType {
    PRODUCT_IMAGE = "product_image",
    BLOG_THUMBNAIL = "blog_thumbnail",
    MARKETING_BANNER = "marketing_banner",
    FNB_IMG_FOOD_HERO = "fnb_img_food_hero",
    FNB_IMG_MENU_DESIGN = "fnb_img_menu_design",
    FNB_IMG_INTERIOR = "fnb_img_interior",
    FNB_IMG_DRINK = "fnb_img_drink",
    FNB_IMG_INGREDIENT = "fnb_img_ingredient",
    FNB_IMG_SOCIAL_POST = "fnb_img_social_post",
    FNB_IMG_BANNER = "fnb_img_banner",
    FNB_IMG_STORY = "fnb_img_story",
    RETAIL_IMG_PRODUCT = "retail_img_product",
    RETAIL_IMG_LIFESTYLE = "retail_img_lifestyle",
    RETAIL_IMG_BANNER = "retail_img_banner",
    RETAIL_IMG_CATEGORY = "retail_img_category",
    RETAIL_IMG_COLLECTION = "retail_img_collection",
    RETAIL_IMG_SOCIAL_POST = "retail_img_social_post",
    RETAIL_IMG_PACKAGING = "retail_img_packaging",
    RETAIL_IMG_MODEL = "retail_img_model",
    HOTEL_IMG_ROOM = "hotel_img_room",
    HOTEL_IMG_EXTERIOR = "hotel_img_exterior",
    HOTEL_IMG_POOL = "hotel_img_pool",
    HOTEL_IMG_DINING = "hotel_img_dining",
    HOTEL_IMG_LOBBY = "hotel_img_lobby",
    HOTEL_IMG_VIEW = "hotel_img_view",
    HOTEL_IMG_BANNER = "hotel_img_banner",
    HOTEL_IMG_SOCIAL_POST = "hotel_img_social_post",
    CLINIC_IMG_FACILITY = "clinic_img_facility",
    CLINIC_IMG_DOCTOR = "clinic_img_doctor",
    CLINIC_IMG_EQUIPMENT = "clinic_img_equipment",
    CLINIC_IMG_TREATMENT = "clinic_img_treatment",
    CLINIC_IMG_RECEPTION = "clinic_img_reception",
    CLINIC_IMG_BANNER = "clinic_img_banner",
    CLINIC_IMG_SOCIAL_POST = "clinic_img_social_post",
    CLINIC_IMG_INFOGRAPHIC = "clinic_img_infographic",
    WELLNESS_IMG_SPA_ROOM = "wellness_img_spa_room",
    WELLNESS_IMG_TREATMENT = "wellness_img_treatment",
    WELLNESS_IMG_THERAPIST = "wellness_img_therapist",
    WELLNESS_IMG_AMBIANCE = "wellness_img_ambiance",
    WELLNESS_IMG_FITNESS = "wellness_img_fitness",
    WELLNESS_IMG_PRODUCT = "wellness_img_product",
    WELLNESS_IMG_BANNER = "wellness_img_banner",
    WELLNESS_IMG_SOCIAL_POST = "wellness_img_social_post",
    SERVICE_IMG_VENUE = "service_img_venue",
    SERVICE_IMG_ACTIVITY = "service_img_activity",
    SERVICE_IMG_EQUIPMENT = "service_img_equipment",
    SERVICE_IMG_GROUP = "service_img_group",
    SERVICE_IMG_INTERIOR = "service_img_interior",
    SERVICE_IMG_EXTERIOR = "service_img_exterior",
    SERVICE_IMG_BANNER = "service_img_banner",
    SERVICE_IMG_SOCIAL_POST = "service_img_social_post"
}
export declare enum AIImageStyle {
    LIFESTYLE = "lifestyle",
    STUDIO = "studio",
    MINIMAL = "minimal",
    CREATIVE = "creative"
}
export declare enum AIImageQuality {
    STANDARD = "standard",
    HD = "hd"
}
export declare enum AIImageProvider {
    IMAGEN = "imagen",
    FLUX_SCHNELL = "flux_schnell",
    FLUX_DEV = "flux_dev",
    IDEOGRAM = "ideogram"
}
export declare enum AIImageOperation {
    GENERATE = "generate",
    EDIT = "edit",
    REMIX = "remix",
    REFRAME = "reframe"
}
export declare enum AIImageRenderingSpeed {
    TURBO = "TURBO",
    BALANCED = "BALANCED",
    QUALITY = "QUALITY"
}
export declare enum AIImageIdeogramStyleType {
    AUTO = "AUTO",
    GENERAL = "GENERAL",
    REALISTIC = "REALISTIC",
    DESIGN = "DESIGN",
    FICTION = "FICTION"
}
