"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ticket_categories = exports.notify = exports.namespace = exports.languages = exports.groups = exports.device = exports.device_variant = exports.device_category = exports.departments = exports.customer = exports.crm_kpis_team_comparison = exports.crm_kpis_analytics = exports.crm_kpis_hierarchy = exports.crm_kpis_stats = exports.crm_kpis = exports.crm = exports.global_configs = exports.companies = exports.api_keys = exports.health_check = exports.activities = exports.payments = exports.sync_report = exports.reports = exports.reconciliation_transactions = exports.reconciliations = exports.reconciliation_payments = exports.order_reconciliations = exports.fulfillments = exports.subscriptions = exports.shops = exports.shipping_methods = exports.sales_channels = exports.receipts = exports.vouchers = exports.promotions = exports.print_template = exports.payment_methods = exports.packages = exports.category_print_template = exports.category_business = exports.business_types = exports.application_plan = exports.application_main = exports.app_controller = exports.app_category_controller = exports.application = exports.application_category = exports.comments = exports.auth = void 0;
exports.cms = exports.warehouses = exports.utm_tags = exports.utm_sources = exports.utm_mediums = exports.utm_link_clicks = exports.utm_links = exports.utm_campaigns = exports.users = exports.translation_key = exports.translation = exports.tickets = exports.ticket_comments = void 0;
exports.auth = __importStar(require("./auth"));
exports.comments = __importStar(require("./comments"));
exports.application_category = __importStar(require("./application_category"));
exports.application = __importStar(require("./application"));
exports.app_category_controller = __importStar(require("./app_category_controller"));
exports.app_controller = __importStar(require("./app_controller"));
exports.application_main = __importStar(require("./application_main"));
exports.application_plan = __importStar(require("./application_plan"));
exports.business_types = __importStar(require("./business_types"));
exports.category_business = __importStar(require("./category_business"));
exports.category_print_template = __importStar(require("./category_print_template"));
exports.packages = __importStar(require("./packages"));
exports.payment_methods = __importStar(require("./payment_methods"));
exports.print_template = __importStar(require("./print_template"));
exports.promotions = __importStar(require("./promotions"));
exports.vouchers = __importStar(require("./vouchers"));
exports.receipts = __importStar(require("./receipts"));
exports.sales_channels = __importStar(require("./sales_channels"));
exports.shipping_methods = __importStar(require("./shipping_methods"));
exports.shops = __importStar(require("./shops"));
exports.subscriptions = __importStar(require("./subscriptions"));
exports.fulfillments = __importStar(require("./fulfillments"));
exports.order_reconciliations = __importStar(require("./order_reconciliations"));
exports.reconciliation_payments = __importStar(require("./reconciliation_payments"));
exports.reconciliations = __importStar(require("./reconciliations"));
exports.reconciliation_transactions = __importStar(require("./reconciliation_transactions"));
exports.reports = __importStar(require("./reports"));
exports.sync_report = __importStar(require("./sync_report"));
exports.payments = __importStar(require("./payments"));
exports.activities = __importStar(require("./activities"));
exports.health_check = __importStar(require("./health_check"));
exports.api_keys = __importStar(require("./api_keys"));
exports.companies = __importStar(require("./companies"));
exports.global_configs = __importStar(require("./global_configs"));
exports.crm = __importStar(require("./crm"));
exports.crm_kpis = __importStar(require("./crm_kpis"));
exports.crm_kpis_stats = __importStar(require("./crm_kpis_stats"));
exports.crm_kpis_hierarchy = __importStar(require("./crm_kpis_hierarchy"));
exports.crm_kpis_analytics = __importStar(require("./crm_kpis_analytics"));
exports.crm_kpis_team_comparison = __importStar(require("./crm_kpis_team_comparison"));
exports.customer = __importStar(require("./customer"));
exports.departments = __importStar(require("./departments"));
exports.device_category = __importStar(require("./device_category"));
exports.device_variant = __importStar(require("./device_variant"));
exports.device = __importStar(require("./device"));
exports.groups = __importStar(require("./groups"));
exports.languages = __importStar(require("./languages"));
exports.namespace = __importStar(require("./namespace"));
exports.notify = __importStar(require("./notify"));
exports.ticket_categories = __importStar(require("./ticket_categories"));
exports.ticket_comments = __importStar(require("./ticket_comments"));
exports.tickets = __importStar(require("./tickets"));
exports.translation = __importStar(require("./translation"));
exports.translation_key = __importStar(require("./translation_key"));
exports.users = __importStar(require("./users"));
exports.utm_campaigns = __importStar(require("./utm_campaigns"));
exports.utm_links = __importStar(require("./utm_links"));
exports.utm_link_clicks = __importStar(require("./utm_link_clicks"));
exports.utm_mediums = __importStar(require("./utm_mediums"));
exports.utm_sources = __importStar(require("./utm_sources"));
exports.utm_tags = __importStar(require("./utm_tags"));
exports.warehouses = __importStar(require("./warehouses"));
exports.cms = __importStar(require("./cms"));
//# sourceMappingURL=index.js.map